// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIX-ORbKLcS01xPEEZFUQYKf8_fNsvGlE',
    appId: '1:1091368786797:web:4d9680d0dfc2ae41b85864',
    messagingSenderId: '1091368786797',
    projectId: 'urdhitracker',
    authDomain: 'urdhitracker.firebaseapp.com',
    storageBucket: 'urdhitracker.firebasestorage.app',
    measurementId: 'G-3S8F711P9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7VP4qqTZG41_2gaRJfUQ57XxDOzMpkNY',
    appId: '1:1091368786797:android:62a28aaecd40fab2b85864',
    messagingSenderId: '1091368786797',
    projectId: 'urdhitracker',
    storageBucket: 'urdhitracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAn4X0XnxubeuLAiWsX--YFV2fMKyn2F8',
    appId: '1:1091368786797:ios:fc2081d39152a66cb85864',
    messagingSenderId: '1091368786797',
    projectId: 'urdhitracker',
    storageBucket: 'urdhitracker.firebasestorage.app',
    iosBundleId: 'com.urdhi.speechnotebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAn4X0XnxubeuLAiWsX--YFV2fMKyn2F8',
    appId: '1:1091368786797:ios:fc2081d39152a66cb85864',
    messagingSenderId: '1091368786797',
    projectId: 'urdhitracker',
    storageBucket: 'urdhitracker.firebasestorage.app',
    iosBundleId: 'com.urdhi.speechnotebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIX-ORbKLcS01xPEEZFUQYKf8_fNsvGlE',
    appId: '1:1091368786797:web:353136ef16b854deb85864',
    messagingSenderId: '1091368786797',
    projectId: 'urdhitracker',
    authDomain: 'urdhitracker.firebaseapp.com',
    storageBucket: 'urdhitracker.firebasestorage.app',
    measurementId: 'G-R71CDGQ0BK',
  );
}
